{{-- The Login Details card, inside an Add/Edit form.

     Exactly two inputs, as asked: the username the person signs in with, and
     their password. It sits at the foot of the form, immediately above Save,
     because creating the account and creating its login are one act for a
     School Admin.

     Both are optional here. A school records a teacher before it decides to
     give them portal access, and a form that refused to save a staff member
     without a password would make the two inseparable. Filling the password
     sets it; leaving it blank leaves whatever was there alone, so editing
     someone's phone number does not silently wipe their login.

     The username is bound to the same Alpine state as the identifier field
     higher up the form (Staff ID, Admission Number, phone), so the two cannot
     drift: there is one login identifier, shown in the two places it matters.

     The password is never rendered back. It is typed here, hashed, and passed
     on by the School Admin. --}}
@props([
    'usernameLabel' => 'Username',
    'usernameModel',
    'usernameHint' => null,
    'passwordHint' => 'Leave blank to keep the current password.',
])

<div
    class="rounded-[8px] border border-primary-100 bg-primary-50/40 p-4 dark:border-primary-900/40 dark:bg-primary-900/10"
    x-data="{ showLoginPassword: false }"
>
    <h4 class="flex items-center gap-2 text-sm font-bold text-gray-900 dark:text-white">
        <i class="fa-solid fa-key text-primary-500"></i>
        Login Details
    </h4>
    <small class="field-hint mt-0.5">
        {{ $usernameHint ?? 'The credentials this person signs in with.' }}
    </small>

    <div class="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2">
        <div>
            <label class="field-label">{{ $usernameLabel }}</label>

            {{-- Shown, never typed. The ID is generated by the system and is
                 not the School Admin's to change: it is what the person signs
                 in with, what their records are filed under, and what the
                 staff numbering keeps in sequence. An editable field here
                 would be an invitation to break all three.

                 Deliberately not a disabled <input> either, a disabled input
                 submits nothing, which is right, but reads as a field that is
                 temporarily unavailable rather than one that is not yours. --}}
            <p class="mt-1 flex h-[36px] items-center rounded-[8px] border border-dashed border-[#CBD6E6] bg-white px-3 font-mono text-[12.5px] text-[#0F2A5C] dark:border-gray-600 dark:bg-gray-900/40 dark:text-gray-200">
                <span x-text="{{ $usernameModel }} || 'Generated on save'"></span>
            </p>
            <small class="field-hint mt-1">Generated automatically &mdash; cannot be edited.</small>
        </div>

        <div>
            <label class="field-label">Password</label>
            <div class="relative mt-1">
                <input
                    :type="showLoginPassword ? 'text' : 'password'"
                    type="password"
                    name="login_password"
                    autocomplete="new-password"
                    class="pr-9"
                >
                <button
                    type="button"
                    @click="showLoginPassword = ! showLoginPassword"
                    tabindex="-1"
                    :aria-label="showLoginPassword ? 'Hide password' : 'Show password'"
                    class="absolute right-0 top-0 flex w-9 items-center justify-center text-[#9AAAC4] transition hover:text-[#5B7099]"
                    style="height: var(--field-height);"
                >
                    <i class="fa-solid text-[12px]" :class="showLoginPassword ? 'fa-eye-slash' : 'fa-eye'"></i>
                </button>
            </div>
            <small class="field-hint mt-1">{{ $passwordHint }}</small>
        </div>
    </div>
</div>
