<?php

use App\Enums\PlanKey;
use App\Enums\StaffRole;
use App\Enums\UserRole;
use App\Models\School;
use App\Models\Staff;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;

/**
 * Teachers sign in on every plan, so their account management is not
 * plan-gated. These tests hold that for BASIC specifically, because the
 * question asked was whether it works there, and a rule nobody asserts is a
 * rule that quietly acquires an exception.
 */
beforeEach(function () {
    $this->school = activateSchool(School::factory()->create(['name' => 'Greenfield College']), PlanKey::Basic);
    $this->admin = User::factory()->create(['role' => UserRole::SchoolAdmin, 'school_id' => $this->school->id]);

    $this->teacher = Staff::factory()->create([
        'school_id' => $this->school->id,
        'role' => StaffRole::Teacher,
        'first_name' => 'Ada',
        'last_name' => 'Obi',
        'is_active' => true,
    ]);
});

test('a Basic school admin sees the login details card on a teacher\'s page', function () {
    $this->actingAs($this->admin)
        ->get(route('staff.show', $this->teacher))
        ->assertOk()
        ->assertSee('Staff ID')
        ->assertSee($this->teacher->staff_number)
        ->assertSee('WhatsApp');
});

test('the Staff ID is shown but cannot be edited', function () {
    // Generated by the system. The School Admin sets a password and nothing
    // else about the identifier.
    $this->actingAs($this->admin)
        ->get(route('staff.show', $this->teacher))
        ->assertOk()
        ->assertSee('Generated automatically and cannot be edited');
});

test('a Basic school admin can set a teacher\'s password', function () {
    $this->actingAs($this->admin)
        ->put(route('staff.update-password', $this->teacher), [
            'password' => 'Correct-Horse1!',
        ])
        ->assertSessionHasNoErrors();

    expect(Hash::check('Correct-Horse1!', $this->teacher->fresh()->password))->toBeTrue();
});

test('the WhatsApp share carries the school, the teacher, the ID and the link', function () {
    $response = $this->actingAs($this->admin)
        ->put(route('staff.credentials', $this->teacher), [
            'password' => 'Correct-Horse1!',
            'password_confirmation' => 'Correct-Horse1!',
        ]);

    $response->assertSessionHasNoErrors();

    $share = session('credential_share');

    expect($share)->not->toBeNull();

    $message = urldecode((string) ($share['url'] ?? ''));

    expect($message)->toContain('Greenfield College')
        ->and($message)->toContain('Ada Obi')
        ->and($message)->toContain($this->teacher->fresh()->staff_number)
        ->and($message)->toContain('Correct-Horse1!')
        ->and($message)->toContain('http');
});

test('a Basic teacher has no self-service password change', function () {
    // The rule from the brief: a teacher who forgets their password goes to
    // their School Admin. There is no route for them to do it themselves.
    expect(Route::has('staff.password.update'))->toBeFalse()
        ->and(Route::has('staff.settings.password'))->toBeFalse();

    $this->actingAs($this->teacher, 'staff')
        ->get(route('staff.settings.index', $this->school))
        ->assertOk()
        ->assertDontSee('Change Password')
        ->assertDontSee('Reset Password');
});

test('one school admin cannot touch another school\'s teacher', function () {
    $otherSchool = activateSchool(School::factory()->create(), PlanKey::Basic);
    $otherAdmin = User::factory()->create(['role' => UserRole::SchoolAdmin, 'school_id' => $otherSchool->id]);

    $this->actingAs($otherAdmin)
        ->put(route('staff.update-password', $this->teacher), ['password' => 'Correct-Horse1!'])
        ->assertForbidden();
});
